# Generated by Django 2.1.8 on 2020-03-21 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_blog_gender'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='gender',
        ),
        migrations.AddField(
            model_name='user',
            name='avatar_url',
            field=models.CharField(max_length=256, null=True, verbose_name='头像路径'),
        ),
        migrations.AddField(
            model_name='user',
            name='gender',
            field=models.SmallIntegerField(choices=[(0, '男'), (1, '女')], default=0, verbose_name='性别'),
        ),
    ]
