# Generated by Django 2.1.8 on 2020-03-22 03:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_auto_20200321_2255'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='comment',
            options={'verbose_name': '微博评论', 'verbose_name_plural': 'verbose_name'},
        ),
        migrations.AddField(
            model_name='blog',
            name='clicks',
            field=models.IntegerField(default=0, verbose_name='浏览量'),
        ),
    ]
