# Generated by Django 2.1.8 on 2020-03-22 07:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0005_auto_20200322_1130'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='allow',
            field=models.BooleanField(default=False, verbose_name='同意协议'),
        ),
    ]
