# Generated by Django 2.1.8 on 2020-03-25 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_auto_20200325_1621'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 16, 29, 9, 912878), verbose_name='注册时间'),
        ),
    ]
