# Generated by Django 2.1.8 on 2020-03-25 08:29

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0009_blog_register_time'),
    ]

    operations = [
        migrations.AlterField(
            model_name='blog',
            name='register_time',
            field=models.DateTimeField(default=datetime.datetime(2020, 3, 25, 16, 29, 45, 772758), verbose_name='注册时间'),
        ),
    ]
