# Generated by Django 2.1.8 on 2020-03-25 08:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0010_auto_20200325_1629'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='blog',
            name='register_time',
        ),
    ]
